//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcLimat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PRUEBACROMATOGRAFICA
    {
        public int idPruebaCroma { get; set; }
        public string idEquipo { get; set; }
        public string dioxidoCarbono { get; set; }
        public string acetileno { get; set; }
        public string etileno { get; set; }
        public string etano { get; set; }
        public string metano { get; set; }
        public string monoxidoCarbono { get; set; }
        public string hidrogeno { get; set; }
        public string totalGasesCombusibles { get; set; }
    
        public virtual tbl_EQUIPO tbl_EQUIPO { get; set; }
    }
}
