//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcLimat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_REPORTE
    {
        public string codigoMuestra { get; set; }
        public string idCliente { get; set; }
        public string cliente { get; set; }
        public string equipo { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string lugarMuestreo { get; set; }
        public string tipoMuestra { get; set; }
        public string procMuestreo { get; set; }
        public string recolectorMuestra { get; set; }
        public string fechaMuestreo { get; set; }
        public string fechaPruebaPBC { get; set; }
        public string condAmbientales { get; set; }
    
        public virtual tbl_CLIENTES tbl_CLIENTES { get; set; }
        public virtual tbl_EQUIPO tbl_EQUIPO { get; set; }
    }
}
