//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcLimat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MANTENIMIENTO
    {
        public int idMantenimiento { get; set; }
        public string idEquipo { get; set; }
        public string tipoMantenimiento { get; set; }
        public string descripcion { get; set; }
        public string supervisor { get; set; }
        public string fecha { get; set; }
    
        public virtual tbl_EQUIPO tbl_EQUIPO { get; set; }
    }
}
